### ISSUE TITLE
I could not use the library

### ISSUE THREAD

**Issue by alejotima** [lubo/zxinglight#1]
lubo first of all I love your project, but I have had problems when it comes to installing and using the library

```
$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from . import read_codes, BarcodeType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'read_codes'
>>> from zxinglight import read_codes, BarcodeType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zxinglight/__init__.py", line 6, in <module>
    from ._zxinglight import zxing_read_codes
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zxinglight/_zxinglight.cpython-36m-darwin.so, 2): Symbol not found: _libiconv
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zxinglight/_zxinglight.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zxinglight/_zxinglight.cpython-36m-darwin.so
```

I appreciate an early help. regards

**Comment by lubo** [comment]
Hi. Unfortunately, I don't use macOS but this seems like a linking issue to me. I've noticed folks have been having similar issues in [another project](https://github.com/openai/universe/issues/139), perhaps you'll find some information there.
